// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.8.0
// source: github.com/rgraphql/demo/app/service/service.proto

package app_service

import (
	_ "github.com/rgraphql/rgraphql"
)
