// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/rgraphql/demo/app/service/service.proto (package app.service, syntax proto3)
/* eslint-disable */

export const protobufPackage = 'app.service'
